#!/command/with-contenv bash
set -euo pipefail

CYAN='\033[1;36m'
GREEN='\033[0;32m'
NC='\033[0m'

ENV_FILE="/code/.env"

echo -e "${CYAN}Generating SimpleLogin .env configuration...${NC}"

DB_URI_VALUE="${DB_URI:-$(cat /var/run/s6/container_environment/DB_URI 2>/dev/null || true)}"
REDIS_URL_VALUE="${REDIS_URL:-$(cat /var/run/s6/container_environment/REDIS_URL 2>/dev/null || true)}"
EMAIL_SERVERS_VALUE="${EMAIL_SERVERS_WITH_PRIORITY:-[(10, \"mail.${EMAIL_DOMAIN}.\")]}"
PARTNER_API_TOKEN_SECRET_VALUE="${PARTNER_API_TOKEN_SECRET:-${FLASK_SECRET}}"

> "$ENV_FILE"

cat >>"$ENV_FILE" <<EOF
URL=${URL}
EMAIL_DOMAIN=${EMAIL_DOMAIN}
SUPPORT_EMAIL=${SUPPORT_EMAIL}
FLASK_SECRET=${FLASK_SECRET}
DB_URI=${DB_URI_VALUE}
REDIS_URL=${REDIS_URL_VALUE}
POSTFIX_SERVER=127.0.0.1
POSTFIX_PORT=${POSTFIX_PORT:-25}
DKIM_PRIVATE_KEY_PATH=/dkim.key
DKIM_PUBLIC_KEY_PATH=/dkim.pub.key
GNUPGHOME=/pgp
WORDS_FILE_PATH=/code/local_data/test_words.txt
LOCAL_FILE_UPLOAD=${LOCAL_FILE_UPLOAD:-true}
DISABLE_ALIAS_SUFFIX=${DISABLE_ALIAS_SUFFIX:-1}
DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-0}
DISABLE_ONBOARDING=${DISABLE_ONBOARDING:-true}
MAX_NB_EMAIL_FREE_PLAN=${MAX_NB_EMAIL_FREE_PLAN:-10}
ENFORCE_SPF=${ENFORCE_SPF:-true}
NOT_SEND_EMAIL=${NOT_SEND_EMAIL:-false}
EMAIL_SERVERS_WITH_PRIORITY=${EMAIL_SERVERS_VALUE}
PARTNER_API_TOKEN_SECRET=${PARTNER_API_TOKEN_SECRET_VALUE}
EOF

if [ -n "${SL_NAMESERVERS:-}" ]; then
    echo "NAMESERVERS=${SL_NAMESERVERS}" >> "$ENV_FILE"
elif [ -n "${NAMESERVERS:-}" ]; then
    echo "NAMESERVERS=${NAMESERVERS}" >> "$ENV_FILE"
else
    echo "NAMESERVERS=1.1.1.1,1.0.0.1" >> "$ENV_FILE"
fi

for optional_var in \
    TEMP_DIR COLOR_LOG LANDING_PAGE_URL STATUS_PAGE_URL ALLOWED_REDIRECT_DOMAINS \
    OTHER_ALIAS_DOMAINS ALIAS_DOMAINS PREMIUM_ALIAS_DOMAINS FIRST_ALIAS_DOMAIN \
    SUPPORT_NAME ADMIN_EMAIL POSTMASTER PGP_SENDER_PRIVATE_KEY_PATH \
    OPENID_PRIVATE_KEY_PATH OPENID_PUBLIC_KEY_PATH ALIAS_LIMIT ALIAS_AUTOMATIC_DISABLE \
    BOUNCE_PREFIX BOUNCE_SUFFIX BOUNCE_PREFIX_FOR_REPLY_PHASE GITHUB_CLIENT_ID \
    GITHUB_CLIENT_SECRET GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET FACEBOOK_CLIENT_ID \
    FACEBOOK_CLIENT_SECRET PROTON_CLIENT_ID PROTON_CLIENT_SECRET PROTON_BASE_URL \
    PROTON_VALIDATE_CERTS CONNECT_WITH_PROTON CONNECT_WITH_PROTON_COOKIE_NAME \
    CONNECT_WITH_OIDC_ICON OIDC_WELL_KNOWN_URL OIDC_SCOPES OIDC_NAME_FIELD \
    OIDC_CLIENT_ID OIDC_CLIENT_SECRET APPLE_API_SECRET MACAPP_APPLE_API_SECRET \
    ENABLE_SPAM_ASSASSIN SPAMASSASSIN_HOST HCAPTCHA_SECRET HCAPTCHA_SITEKEY \
    PLAUSIBLE_HOST PLAUSIBLE_DOMAIN SENTRY_DSN SENTRY_FRONT_END_DSN FLASK_PROFILER_PATH \
    FLASK_PROFILER_PASSWORD HIBP_SCAN_INTERVAL_DAYS HIBP_API_KEYS BUCKET AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY AWS_REGION PADDLE_VENDOR_ID PADDLE_MONTHLY_PRODUCT_ID \
    PADDLE_YEARLY_PRODUCT_ID PADDLE_PUBLIC_KEY_PATH PADDLE_AUTH_CODE COINBASE_WEBHOOK_SECRET \
    COINBASE_CHECKOUT_ID COINBASE_API_KEY COINBASE_YEARLY_PRICE
do
    if [ -n "${!optional_var:-}" ]; then
        echo "${optional_var}=${!optional_var}" >> "$ENV_FILE"
    fi
done

chmod 600 "$ENV_FILE"

echo -e "${GREEN}Successfully generated ${ENV_FILE}${NC}"
