#!/command/with-contenv bash
# shellcheck shell=bash
set -euo pipefail
source /etc/simplelogin-aio/env-helpers.sh
normalize_simplelogin_presence_env_vars

CYAN='\033[1;36m'
GREEN='\033[0;32m'
NC='\033[0m'

ENV_FILE="/code/.env"

echo -e "${CYAN}Generating SimpleLogin .env configuration...${NC}"

DB_URI_VALUE="${DB_URI:-$(cat /var/run/s6/container_environment/DB_URI 2>/dev/null || true)}"
REDIS_URL_VALUE="${REDIS_URL:-$(cat /var/run/s6/container_environment/REDIS_URL 2>/dev/null || true)}"
EMAIL_SERVERS_VALUE="${EMAIL_SERVERS_WITH_PRIORITY:-[(10, \"mail.${EMAIL_DOMAIN}.\")]}"
PARTNER_API_TOKEN_SECRET_VALUE="${PARTNER_API_TOKEN_SECRET:-${FLASK_SECRET}}"
POSTFIX_SERVER_VALUE="${POSTFIX_SERVER:-127.0.0.1}"
POSTFIX_PORT_VALUE="${POSTFIX_PORT:-25}"
DKIM_PRIVATE_KEY_PATH_VALUE="${DKIM_PRIVATE_KEY_PATH:-/dkim.key}"
GNUPGHOME_VALUE="${GNUPGHOME:-/pgp}"
WORDS_FILE_PATH_VALUE="${WORDS_FILE_PATH:-/code/local_data/test_words.txt}"

emit_presence_var() {
    local name="$1"
    if is_truthy_env_value "${!name:-}"; then
        echo "${name}=${!name}" >> "$ENV_FILE"
    fi
}

: > "$ENV_FILE"

cat >>"$ENV_FILE" <<EOF
URL=${URL}
EMAIL_DOMAIN=${EMAIL_DOMAIN}
SUPPORT_EMAIL=${SUPPORT_EMAIL}
FLASK_SECRET=${FLASK_SECRET}
DB_URI=${DB_URI_VALUE}
REDIS_URL=${REDIS_URL_VALUE}
POSTFIX_SERVER=${POSTFIX_SERVER_VALUE}
POSTFIX_PORT=${POSTFIX_PORT_VALUE}
DKIM_PRIVATE_KEY_PATH=${DKIM_PRIVATE_KEY_PATH_VALUE}
DKIM_PUBLIC_KEY_PATH=/dkim.pub.key
GNUPGHOME=${GNUPGHOME_VALUE}
WORDS_FILE_PATH=${WORDS_FILE_PATH_VALUE}
MAX_NB_EMAIL_FREE_PLAN=${MAX_NB_EMAIL_FREE_PLAN:-10}
EMAIL_SERVERS_WITH_PRIORITY=${EMAIL_SERVERS_VALUE}
PARTNER_API_TOKEN_SECRET=${PARTNER_API_TOKEN_SECRET_VALUE}
EOF

for presence_var in \
    COLOR_LOG NOT_SEND_EMAIL ENFORCE_SPF DISABLE_ALIAS_SUFFIX DISABLE_REGISTRATION \
    DISABLE_ONBOARDING PROTON_VALIDATE_CERTS CONNECT_WITH_PROTON LOCAL_FILE_UPLOAD \
    ENABLE_SPAM_ASSASSIN ALIAS_AUTOMATIC_DISABLE POSTFIX_SUBMISSION_TLS \
    LOAD_PGP_EMAIL_HANDLER APPLE_WEBHOOK_SECRET_CHECK_ENABLED RSPAMD_SIGN_DKIM \
    DMARC_CHECK_ENABLED PROTON_PREVENT_CHANGE_LINKED_ACCOUNT \
    ENABLE_ALL_REVERSE_ALIAS_REPLACEMENT DISABLE_RATE_LIMIT \
    STORE_TRANSACTIONAL_EMAILS EVENT_WEBHOOK_SKIP_VERIFY_SSL EVENT_WEBHOOK_DISABLE \
    USE_RUST_PGP ZENDESK_ENABLED DROP_PGP_KEY_ATTACHMENTS_ON_REPLY
do
    emit_presence_var "$presence_var"
done

if [ -n "${SL_NAMESERVERS:-}" ]; then
    echo "NAMESERVERS=${SL_NAMESERVERS}" >> "$ENV_FILE"
elif [ -n "${NAMESERVERS:-}" ]; then
    echo "NAMESERVERS=${NAMESERVERS}" >> "$ENV_FILE"
else
    echo "NAMESERVERS=1.1.1.1,1.0.0.1" >> "$ENV_FILE"
fi

for optional_var in \
    TEMP_DIR COLOR_LOG LANDING_PAGE_URL STATUS_PAGE_URL ALLOWED_REDIRECT_DOMAINS \
    OTHER_ALIAS_DOMAINS ALIAS_DOMAINS PREMIUM_ALIAS_DOMAINS FIRST_ALIAS_DOMAIN \
    SUPPORT_NAME ADMIN_EMAIL POSTMASTER PGP_SENDER_PRIVATE_KEY_PATH \
    OPENID_PRIVATE_KEY_PATH OPENID_PUBLIC_KEY_PATH ALIAS_LIMIT ALIAS_AUTOMATIC_DISABLE \
    BOUNCE_PREFIX BOUNCE_SUFFIX BOUNCE_PREFIX_FOR_REPLY_PHASE GITHUB_CLIENT_ID \
    GITHUB_CLIENT_SECRET GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET FACEBOOK_CLIENT_ID \
    FACEBOOK_CLIENT_SECRET PROTON_CLIENT_ID PROTON_CLIENT_SECRET PROTON_BASE_URL \
    PROTON_VALIDATE_CERTS CONNECT_WITH_PROTON CONNECT_WITH_PROTON_COOKIE_NAME \
    CONNECT_WITH_OIDC_ICON OIDC_WELL_KNOWN_URL OIDC_SCOPES OIDC_NAME_FIELD \
    OIDC_CLIENT_ID OIDC_CLIENT_SECRET APPLE_API_SECRET MACAPP_APPLE_API_SECRET \
    ENABLE_SPAM_ASSASSIN SPAMASSASSIN_HOST HCAPTCHA_SECRET HCAPTCHA_SITEKEY \
    PLAUSIBLE_HOST PLAUSIBLE_DOMAIN SENTRY_DSN SENTRY_FRONT_END_DSN FLASK_PROFILER_PATH \
    FLASK_PROFILER_PASSWORD HIBP_SCAN_INTERVAL_DAYS HIBP_API_KEYS BUCKET AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY AWS_REGION PADDLE_VENDOR_ID PADDLE_MONTHLY_PRODUCT_ID \
    PADDLE_YEARLY_PRODUCT_ID PADDLE_PUBLIC_KEY_PATH PADDLE_AUTH_CODE COINBASE_WEBHOOK_SECRET \
    COINBASE_CHECKOUT_ID COINBASE_API_KEY COINBASE_YEARLY_PRICE \
    MONITORING_EMAIL UNSUBSCRIBER OLD_UNSUBSCRIBER TRANSACTIONAL_BOUNCE_PREFIX \
    TRANSACTIONAL_BOUNCE_SUFFIX POSTFIX_BACKUP_SERVERS POSTFIX_TIMEOUT \
    POSTFIX_CONNECT_TIMEOUT PROTON_MX_SERVERS PROTON_EMAIL_DOMAINS AWS_ENDPOINT_URL \
    PADDLE_MONTHLY_PRODUCT_IDS PADDLE_YEARLY_PRODUCT_IDS PADDLE_COUPON_ID \
    PROTON_EXTRA_HEADER_NAME PROTON_EXTRA_HEADER_VALUE SENTRY_TRACE_RATE \
    MAX_SPAM_SCORE MAX_REPLY_PHASE_SPAM_SCORE PGP_SIGNER NOREPLY PARTNER_NOREPLY \
    HIBP_API_RPM HIBP_SKIP_PARTNER_ALIAS SAVE_UNSENT_DIR TWILIO_AUTH_TOKEN \
    PHONE_PROVIDER_1_SECRET PHONE_PROVIDER_2_HEADER PHONE_PROVIDER_2_SECRET \
    ZENDESK_HOST ZENDESK_API_TOKEN VERP_PREFIX VERP_EMAIL_SECRET \
    ALIAS_TRANSFER_TOKEN_SECRET ALIAS_RAND_SUFFIX_LENGTH MAX_NB_EMAIL_OLD_FREE_PLAN \
    DB_CONN_NAME EVENT_WEBHOOK EVENT_WEBHOOK_ENABLED_USER_IDS EVENT_LISTENER_DB_URI \
    MAX_API_KEYS MEM_STORE_URI RECOVERY_CODE_HMAC_SECRET \
    MIN_RSPAMD_SCORE_FOR_FAILED_DMARC MAX_NB_REVERSE_ALIAS_REPLACEMENT \
    MAX_BOUNCES_1D MAX_BOUNCES_1W PARTNER_DNS_CUSTOM_DOMAINS \
    PARTNER_CUSTOM_DOMAIN_VALIDATION_PREFIXES MAILBOX_VERIFICATION_OVERRIDE_CODE \
    AUDIT_LOG_MAX_DAYS ALIAS_TRASH_DAYS ALLOWED_OAUTH_SCHEMES \
    MAX_EMAIL_FORWARD_RECIPIENTS USERS_WITH_HTTP_UNSUBSCRIBE \
    ALIAS_CREATE_RATE_LIMIT_FREE ALIAS_CREATE_RATE_LIMIT_PAID \
    ALIAS_RESTORE_ONE_RATE_LIMIT ALIAS_RESTORE_ALL_RATE_LIMIT \
    MASTER_ENC_KEY_HEX MAC_KEY_HEX ABUSER_HKDF_SALT \
    INVALID_MX_IPS SMTP_SIZE_LIMIT PARTNER_SUPPORT_URL ADMIN_FIDO_REQUIRED \
    ADMIN_GRACE_PERIOD UPCLOUD_USERNAME UPCLOUD_PASSWORD UPCLOUD_DB_ID \
    DISABLE_CREATE_CONTACTS_FOR_FREE_USERS CONFIG
do
    if [ -n "${!optional_var:-}" ]; then
        echo "${optional_var}=${!optional_var}" >> "$ENV_FILE"
    fi
done

chmod 600 "$ENV_FILE"

echo -e "${GREEN}Successfully generated ${ENV_FILE}${NC}"
