name: Check Upstream Version

on:
  schedule:
    - cron: 23 7 * * 1
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-upstream:
    uses: JSONbored/aio-fleet/.github/workflows/aio-check-upstream.yml@4caf10de3d95ab99b67f65766cd52dd80cb7f75c
    permissions:
      contents: write
      pull-requests: write
      issues: write
    with:
      workflow_title: Check Upstream Version
      component_matrix: '[""]'
      commit_paths: |
        Dockerfile
    secrets: inherit
