name: Publish Release / SimpleLogin-AIO

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-publish-release.yml@ca2c2a32968e0c6d05f0fe270db6a6a48fb32dbf
    permissions:
      actions: read
      contents: write
    with:
      release_name: SimpleLogin-AIO
      component: ""
      workflow_selector: build.yml
    secrets: inherit
