name: Publish Release / SimpleLogin-AIO

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-publish-release.yml@6cb527a4cccd624ad73447b6b73cda9b56b4c9c7
    permissions:
      actions: read
      contents: write
    with:
      release_name: SimpleLogin-AIO
      component: ""
      workflow_selector: build.yml
    secrets: inherit
