name: Publish Release / SimpleLogin-AIO

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-publish-release.yml@4aea17371db2faf5ba759cda63b4f46aac514162
    permissions:
      actions: read
      contents: write
    with:
      release_name: SimpleLogin-AIO
      component: ""
      workflow_selector: build.yml
    secrets: inherit
