name: Prepare Release / SimpleLogin-AIO

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-prepare-release.yml@c4099c09cb2375a0f5a5a822a0f8af02a77d0526
    permissions:
      contents: write
      pull-requests: write
    with:
      release_name: SimpleLogin-AIO
      component: ""
      component_label: ""
      previous_tag_command: latest-aio-tag
    secrets: inherit
