name: Prepare Release / SimpleLogin-AIO

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-prepare-release.yml@a13769d03bb1eade5323709ea4d873874fb78cb2
    permissions:
      contents: write
      pull-requests: write
    with:
      release_name: SimpleLogin-AIO
      component: ""
      component_label: ""
      previous_tag_command: latest-aio-tag
    secrets: inherit
