name: Prepare Release / SimpleLogin-AIO

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-release:
    uses: JSONbored/aio-fleet/.github/workflows/aio-prepare-release.yml@ce6221adb01de3fbe16b40fa0274c950c1ccd225
    permissions:
      contents: write
      pull-requests: write
    with:
      release_name: SimpleLogin-AIO
      component: ""
      component_label: ""
      previous_tag_command: latest-aio-tag
    secrets: inherit
